[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Redirects para SPA behavior en rutas dinámicas
[[redirects]]
  from = "/productos/*"
  to = "/productos/:splat"
  status = 200

[[redirects]]
  from = "/categoria/*"
  to = "/categoria/:splat"
  status = 200

[[redirects]]
  from = "/cuenta/*"
  to = "/cuenta/:splat"
  status = 200

# API Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Headers para seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Headers para assets estáticos (cache)
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers para contenido adulto (compliance)
[[headers]]
  for = "/*"
  [headers.values]
    X-Adult-Content = "true"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://checkout.wompi.co https://www.google-analytics.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://api.airtable.com https://firestore.googleapis.com https://checkout.wompi.co;"

# Edge Functions (para lógica avanzada)
[[edge_functions]]
  function = "geo-redirect"
  path = "/checkout/*"

# Context-specific builds
[context.production]
  command = "npm run build"
  
[context.deploy-preview]
  command = "npm run build"
  
[context.branch-deploy]
  command = "npm run build"

# Plugin de Astro para optimizaciones
[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"
  
  [plugins.inputs]
  baseUrl = "https://kamasex.shop"
  sitemapPath = "/sitemap.xml"
  ignorePeriod = 0
  providers = [
    "google",
    "bing"
  ]
